controller_list:
  - name: fake_arm_controller
    joints:
      - right/shoulder_horizontal
      - right/shoulder_vertical
      - right/axial
      - right/extension
      - right/wrist_vertical
      - right/wrist_horizontal